# Embed compiled SPIR-V modules as a C++ translation unit.
#
# Invoked as a script:
#   cmake -DOUTPUT=<out.cc> -DHEADER=<out.h> -DINPUTS=<a.spv;b.spv> \
#         -P ARTEmbedSpirv.cmake
#
# A CMake -P script rather than a compiled generator on purpose: a
# host-executable helper is exactly the thing that breaks cross-compiled
# MinGW builds.

if(NOT DEFINED OUTPUT OR NOT DEFINED HEADER)
    message(FATAL_ERROR "ARTEmbedSpirv: OUTPUT and HEADER are required")
endif()

set(_decls "")
set(_table "")
set(_count 0)

foreach(_spv ${INPUTS})
    if(NOT EXISTS "${_spv}")
        message(FATAL_ERROR "ARTEmbedSpirv: missing input ${_spv}")
    endif()
    get_filename_component(_name "${_spv}" NAME_WE)

    file(READ "${_spv}" _hex HEX)
    string(LENGTH "${_hex}" _nchars)
    math(EXPR _nbytes "${_nchars} / 2")
    math(EXPR _rem "${_nbytes} % 4")
    if(NOT _rem EQUAL 0)
        message(FATAL_ERROR
            "ARTEmbedSpirv: ${_spv} is ${_nbytes} bytes, not a multiple of 4")
    endif()

    # SPIR-V is a stream of little-endian 32-bit words; file(READ ... HEX)
    # gives bytes in file order, so each group of 4 bytes is byte-swapped
    # back into a word literal.
    string(REGEX MATCHALL "([0-9a-f][0-9a-f])" _bytes "${_hex}")
    set(_words "")
    set(_i 0)
    set(_b0 "")
    set(_b1 "")
    set(_b2 "")
    foreach(_byte ${_bytes})
        math(EXPR _phase "${_i} % 4")
        if(_phase EQUAL 0)
            set(_b0 "${_byte}")
        elseif(_phase EQUAL 1)
            set(_b1 "${_byte}")
        elseif(_phase EQUAL 2)
            set(_b2 "${_byte}")
        else()
            string(APPEND _words "0x${_byte}${_b2}${_b1}${_b0}u,")
            math(EXPR _mod "(${_i} + 1) % 32")
            if(_mod EQUAL 0)
                string(APPEND _words "\n")
            endif()
        endif()
        math(EXPR _i "${_i} + 1")
    endforeach()

    string(APPEND _decls
        "static const unsigned int ${_name}_spv[] = {\n${_words}\n};\n\n")
    string(APPEND _table
        "    { \"${_name}\", ${_name}_spv, ${_nbytes}u },\n")
    math(EXPR _count "${_count} + 1")
endforeach()

get_filename_component(_header_name "${HEADER}" NAME)

file(WRITE "${HEADER}"
"/* Generated by cmake/modules/ARTEmbedSpirv.cmake -- do not edit. */
#ifndef ART_GPU_SHADERS_GENERATED_H
#define ART_GPU_SHADERS_GENERATED_H

struct ArtGPUShader {
    const char *name;
    const unsigned int *words;
    unsigned long size;   /* bytes */
};

extern const unsigned int art_gpu_shader_count;
extern const ArtGPUShader art_gpu_shaders[];

#endif
")

file(WRITE "${OUTPUT}"
"/* Generated by cmake/modules/ARTEmbedSpirv.cmake -- do not edit. */
#include \"${_header_name}\"

${_decls}const ArtGPUShader art_gpu_shaders[] = {
${_table}    { 0, 0, 0u }
};

const unsigned int art_gpu_shader_count = ${_count}u;
")

message(STATUS "ARTEmbedSpirv: embedded ${_count} SPIR-V module(s)")
